version: '3.7'

services:
    php71:
        build: ./php71
        working_dir: /var/www/app/public
        container_name: php71
        restart: always
        volumes:
            - ./php71:/var/www/app
        ports:
            - "8081:8080"
        networks:
            - docker-stack-network

    php72:
        build: ./php72
        working_dir: /var/www/app/public
        container_name: php72
        restart: always
        volumes:
            - ./php72:/var/www/app
        ports:
            - "8082:8080"
        networks:
            - docker-stack-network

    php73:
        build: ./php73
        working_dir: /var/www/app/public
        container_name: php73
        restart: always
        volumes:
            - ./php73:/var/www/app
        ports:
            - "8083:8080"
        networks:
            - docker-stack-network
    php74:
        build: ./php74
        working_dir: /var/www/app/public
        container_name: php74
        restart: always
        volumes:
            - ./php74:/var/www/app
        ports:
            - "8084:8080"
        networks:
            - docker-stack-network

    laravel7:
        build: ./laravel7
        working_dir: /var/www/app/public
        container_name: laravel7
        restart: always
        volumes:
            - ./laravel7:/var/www/app
        ports:
            - "8088:8080"
        networks:
            - docker-stack-network

    symfony5:
        build: ./symfony5
        working_dir: /var/www/app/public
        container_name: symfony5
        restart: always
        volumes:
            - ./symfony5:/var/www/app
        ports:
            - "8089:8080"
        networks:
            - docker-stack-network
networks:
    docker-stack-network:
        driver: bridge
